server:
  port: 8080



spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/se_db
    username: ${software.datasource.username}
    password: ${software.datasource.password}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.software.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      software:
        mapper: debug
        service: info
        controller: info

software:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

