spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: hk040424


mybatis:
  configuration:
    map-underscore-to-camel-case: true

